from django.contrib import admin
from ..models.resume import *
from .post_admin import *
from .contact_admin import *
from .education_admin import *
from .experience_admin import *
from .person_admin import *
from .language_admin import *
from .language_status_admin import *
from .skill_admin import *
from .project_admin import *