# Generated by Django 4.2.7 on 2023-11-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.IntegerField(choices=[(0, 'University'), (1, 'High Scholl')], default=0)),
                ('institute', models.CharField(blank=True, max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Completed'), (1, 'Incompleted')], default=0)),
                ('is_certification', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(max_length=200)),
                ('url_company', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('encoding', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'language status',
                'verbose_name_plural': 'Language status',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=200)),
                ('contact_type', models.IntegerField(choices=[(0, 'Mobile'), (1, 'Email')], default=1)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('subject', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('nacionality', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('education', models.ManyToManyField(blank=True, to='sections.education')),
                ('experience', models.ManyToManyField(blank=True, to='sections.experience')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(0, 'Aptitudes'), (1, 'Certifications'), (2, 'Other Skillls'), (3, 'Soft Skills'), (4, 'Languages')], default=0)),
                ('category', models.IntegerField(choices=[(0, 'Programing Languages'), (1, 'Web Development'), (2, 'Automation'), (3, 'Data Analytics & Visualization'), (4, 'Databases'), (5, 'Management tools'), (6, 'Design tools'), (7, 'Cloud'), (8, 'Other'), (9, 'Data Engineering')], default=0)),
                ('institute', models.CharField(blank=True, max_length=200)),
                ('level', models.IntegerField(choices=[(0, 'Less than a year'), (1, 'Between 1 a 3 years'), (2, 'More than 3 years')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sections.language')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sections.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='lang',
            field=models.ManyToManyField(blank=True, through='sections.TaskLang', to='sections.language'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('lang', models.ManyToManyField(blank=True, to='sections.language')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sections.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('like', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('hashtags', models.TextField(blank=True)),
                ('skill', models.ManyToManyField(blank=True, to='sections.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='post',
            field=models.ManyToManyField(blank=True, to='sections.post'),
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ManyToManyField(blank=True, to='sections.project'),
        ),
        migrations.AddField(
            model_name='person',
            name='skill',
            field=models.ManyToManyField(blank=True, to='sections.skill'),
        ),
        migrations.AddField(
            model_name='person',
            name='social_contact',
            field=models.ManyToManyField(blank=True, to='sections.contact'),
        ),
        migrations.CreateModel(
            name='LanguageStatusLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sections.language')),
                ('language_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sections.languagestatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='languagestatus',
            name='lang',
            field=models.ManyToManyField(blank=True, through='sections.LanguageStatusLang', to='sections.language'),
        ),
        migrations.AddField(
            model_name='language',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sections.languagestatus'),
        ),
        migrations.CreateModel(
            name='ExperienceLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sections.experience')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sections.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='lang',
            field=models.ManyToManyField(blank=True, through='sections.ExperienceLang', to='sections.language'),
        ),
        migrations.AddField(
            model_name='experience',
            name='skill',
            field=models.ManyToManyField(blank=True, to='sections.skill'),
        ),
        migrations.AddField(
            model_name='experience',
            name='task',
            field=models.ManyToManyField(blank=True, to='sections.task'),
        ),
        migrations.CreateModel(
            name='EducationLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sections.education')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sections.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='education',
            name='lang',
            field=models.ManyToManyField(blank=True, through='sections.EducationLang', to='sections.language'),
        ),
    ]
